import Testing
@testable import JboxEngineSwift
@_exported import JboxEngineC

/// Store-level behaviour driven through the real Core Audio engine.
/// The macOS CI runner always has default built-in devices; we never
/// assume specific channel counts, just that enumeration returns at
/// least one device in each direction.
@MainActor
@Suite("EngineStore (live Core Audio)")
struct EngineStoreTests {

    private func makeStore() throws -> EngineStore {
        try EngineStore()
    }

    @Test("refreshDevices populates the observable devices list")
    func refreshDevicesPopulates() throws {
        let store = try makeStore()
        #expect(store.devices.isEmpty)
        store.refreshDevices()
        #expect(!store.devices.isEmpty)
        #expect(store.lastError == nil)
    }

    @Test("device(uid:) looks up a device from the refreshed snapshot")
    func deviceByUidLookup() throws {
        let store = try makeStore()
        store.refreshDevices()
        guard let first = store.devices.first else {
            Issue.record("expected at least one device on CI runner")
            return
        }
        let looked = store.device(uid: first.uid)
        #expect(looked == first)
        #expect(store.device(uid: "no-such-uid") == nil)
    }

    @Test("addRoute with a bogus mapping surfaces JBOX_ERR_MAPPING_INVALID")
    func addRouteInvalidMapping() throws {
        let store = try makeStore()
        store.refreshDevices()
        let src = store.devices.first(where: { $0.directionInput })!
        let dst = store.devices.first(where: { $0.directionOutput })!

        // Empty mapping — v1 invariant violation.
        let cfg = RouteConfig(
            source: DeviceReference(device: src),
            destination: DeviceReference(device: dst),
            mapping: []
        )
        do {
            _ = try store.addRoute(cfg)
            Issue.record("expected MAPPING_INVALID")
        } catch let e as JboxError {
            #expect(e.code == JBOX_ERR_MAPPING_INVALID)
            #expect(store.lastError != nil)
        }
        #expect(store.routes.isEmpty)
    }

    @Test("addRoute with a duplicate source edge is rejected before reaching the engine list")
    func addRouteDuplicateSrc() throws {
        let store = try makeStore()
        store.refreshDevices()
        let src = store.devices.first(where: { $0.directionInput })!
        let dst = store.devices.first(where: { $0.directionOutput })!

        let cfg = RouteConfig(
            source: DeviceReference(device: src),
            destination: DeviceReference(device: dst),
            mapping: [ChannelEdge(src: 0, dst: 0),
                      ChannelEdge(src: 0, dst: 1)]
        )
        do {
            _ = try store.addRoute(cfg)
            Issue.record("expected MAPPING_INVALID")
        } catch let e as JboxError {
            #expect(e.code == JBOX_ERR_MAPPING_INVALID)
        }
        #expect(store.routes.isEmpty)
    }

    @Test("addRoute + removeRoute round-trips through the observable list")
    func addRouteThenRemove() throws {
        let store = try makeStore()
        store.refreshDevices()

        // Pick devices with at least one input channel on one side and
        // one output channel on the other.
        guard let src = store.devices.first(where: { $0.inputChannelCount  >= 1 }),
              let dst = store.devices.first(where: { $0.outputChannelCount >= 1 })
        else {
            Issue.record("CI runner expected to expose at least one input- and one output-capable device")
            return
        }

        let cfg = RouteConfig(
            source: DeviceReference(device: src),
            destination: DeviceReference(device: dst),
            mapping: [ChannelEdge(src: 0, dst: 0)],
            name: "test-round-trip"
        )
        let route = try store.addRoute(cfg)
        #expect(store.routes.count == 1)
        #expect(store.routes.first?.id == route.id)
        #expect(store.routes.first?.status.state == .stopped)

        store.removeRoute(route.id)
        #expect(store.routes.isEmpty)
        #expect(store.lastError == nil)
    }

    @Test("displayName falls back to source → destination when name is nil")
    func routeDisplayNameAutoGenerated() {
        let cfg = RouteConfig(
            source: DeviceReference(uid: "s", lastKnownName: "Source"),
            destination: DeviceReference(uid: "d", lastKnownName: "Dest"),
            mapping: [ChannelEdge(src: 0, dst: 0)]
        )
        #expect(cfg.displayName == "Source → Dest")

        var named = cfg
        named.name = "Live feed"
        #expect(named.displayName == "Live feed")
    }
}
